name: tagpr and Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: false
        type: string

permissions:
  pull-requests: write
  packages: write
  contents: write
  actions: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref }}
      - id: tagpr
        uses: Songmu/tagpr@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - uses: actions/setup-node@v3
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
        with:
          node-version: 20
          cache: yarn

        - name: Install dependencies
          run: yarn install --frozen-lockfile
          if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
        - name: Build website
          if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
          run: yarn build

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
